### ISSUE TITLE
Could not pass event errors

### ISSUE THREAD

**Issue by TheFarmerNL** [mewin-archived/WGPlayerDamageFlags#2]
Hey,

we have Craftbukkit 1.4.2 #2450 and Worldguard Custom Flags version 1.4.
We are receiving the following errors:

2012-11-01 02:26:11 [SEVERE] Could not pass event EntityDamageEvent to WGPlayerDamageFlags v0.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.Entity.burn(Entity.java:810)
    at net.minecraft.server.Entity.move(Entity.java:723)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:379)
    at net.minecraft.server.Packet10Flying.handle(SourceFile:136)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:569)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:486)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
Caused by: java.lang.NullPointerException
    at de.bangl.wgpdf.Utils.dmgAllowedInRegion(Utils.java:120)
    at de.bangl.wgpdf.Utils.dmgAllowedAtLocation(Utils.java:107)
    at de.bangl.wgpdf.listener.PlayerDamageListener.onPlayerDamage(PlayerDamageListener.java:45)
    at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-11-01 02:26:11 [SEVERE] Could not pass event EntityDamageEvent to WGPlayerDamageFlags v0.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.Entity.y(Entity.java:344)
    at net.minecraft.server.EntityLiving.y(EntityLiving.java:300)
    at net.minecraft.server.Entity.j_(Entity.java:228)
    at net.minecraft.server.EntityLiving.j_(EntityLiving.java:474)
    at net.minecraft.server.EntityHuman.j_(EntityHuman.java:154)
    at net.minecraft.server.EntityPlayer.g(EntityPlayer.java:188)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:349)
    at net.minecraft.server.Packet10Flying.handle(SourceFile:136)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:569)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:486)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
Caused by: java.lang.NullPointerException
    at de.bangl.wgpdf.Utils.dmgAllowedInRegion(Utils.java:120)
    at de.bangl.wgpdf.Utils.dmgAllowedAtLocation(Utils.java:107)
    at de.bangl.wgpdf.listener.PlayerDamageListener.onPlayerDamage(PlayerDamageListener.java:45)
    at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 20 more

2012-11-01 02:25:48 [SEVERE] Could not pass event EntityDamageByBlockEvent to WGPlayerDamageFlags v0.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.Entity.A(Entity.java:393)
    at net.minecraft.server.Entity.y(Entity.java:361)
    at net.minecraft.server.EntityLiving.y(EntityLiving.java:300)
    at net.minecraft.server.Entity.j_(Entity.java:228)
    at net.minecraft.server.EntityLiving.j_(EntityLiving.java:474)
    at net.minecraft.server.EntityHuman.j_(EntityHuman.java:154)
    at net.minecraft.server.EntityPlayer.g(EntityPlayer.java:188)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:349)
    at net.minecraft.server.Packet10Flying.handle(SourceFile:136)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:569)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:486)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
Caused by: java.lang.NullPointerException
    at de.bangl.wgpdf.Utils.dmgAllowedInRegion(Utils.java:120)
    at de.bangl.wgpdf.Utils.dmgAllowedAtLocation(Utils.java:107)
    at de.bangl.wgpdf.listener.PlayerDamageListener.onPlayerDamage(PlayerDamageListener.java:45)
    at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 21 more

I hope you can fix this!

Regards,
TheFarmerNL

**Comment by BangL** [comment]
fixed in v0.4
